(add-to-list 'load-path "~/.emacs.d/dotemacs")
(add-to-list 'load-path "~/common/dotemacs")
(add-to-list 'load-path "~/project/common/dotemacs")
(add-to-list 'load-path "c:/common/dotemacs")
(add-to-list 'load-path "c:/project/common/dotemacs")
(add-to-list 'load-path "d:/common/dotemacs")
(add-to-list 'load-path "d:/project/common/dotemacs")
(add-to-list 'load-path "e:/common/dotemacs")
(add-to-list 'load-path "e:/project/common/dotemacs")
(add-to-list 'load-path "f:/common/dotemacs")
(add-to-list 'load-path "f:/project/common/dotemacs")
(require 'init-basic nil t)
(require 'init-site nil t)
(require 'init-misc nil t)
