;;; ecb-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ecb.el

(autoload 'ecb-activate "ecb" "\
Activates ECB and creates the special buffers for the choosen layout.
For the layout see `ecb-layout-name'. This function raises always the
ECB-frame if called from another frame. This is the same as calling
`ecb-minor-mode' with a positive argument." t)
(autoload 'ecb-minor-mode "ecb" "\
Toggle ECB minor mode.
With prefix argument ARG, turn on if positive, otherwise off. Return non-nil
if the minor mode is enabled.

\\{ecb-mode-map}

(fn &optional ARG)" t)
(autoload 'ecb-byte-compile "ecb" "\
Byte-compiles the ECB package.
This is done for all lisp-files of ECB if FORCE-ALL is not nil or for each
lisp-file FILE.el which is either newer than FILE.elc or if FILE.elc doesn't
exist.

(fn &optional FORCE-ALL)" t)
(register-definition-prefixes "ecb" '("ecb-"))


;;; Generated autoloads from ecb-advice-test.el

(register-definition-prefixes "ecb-advice-test" '("ecb-"))


;;; Generated autoloads from ecb-analyse.el

(register-definition-prefixes "ecb-analyse" '("ecb-"))


;;; Generated autoloads from ecb-autogen.el

(register-definition-prefixes "ecb-autogen" '("ecb-"))


;;; Generated autoloads from ecb-cedet-wrapper.el

(register-definition-prefixes "ecb-cedet-wrapper" '("ecb-"))


;;; Generated autoloads from ecb-common-browser.el

(register-definition-prefixes "ecb-common-browser" '("defecb-" "delete-frame" "ecb-"))


;;; Generated autoloads from ecb-compatibility.el

(register-definition-prefixes "ecb-compatibility" '("Electric-pop-up-window" "ecb-" "electric-" "master-says" "one-window-p" "scroll-all-function-all" "tmm-prompt" "view-mode-exit"))


;;; Generated autoloads from ecb-compilation.el

(register-definition-prefixes "ecb-compilation" '("ecb-compilation-"))


;;; Generated autoloads from ecb-create-layout.el

(register-definition-prefixes "ecb-create-layout" '("ecb-"))


;;; Generated autoloads from ecb-eshell.el

(register-definition-prefixes "ecb-eshell" '("ecb-eshell-" "eshell"))


;;; Generated autoloads from ecb-examples.el

(register-definition-prefixes "ecb-examples" '("ecb-"))


;;; Generated autoloads from ecb-face.el

(register-definition-prefixes "ecb-face" '("ecb-"))


;;; Generated autoloads from ecb-file-browser.el

(register-definition-prefixes "ecb-file-browser" '("clearcase-sync-from-disk" "ecb-" "vc-checkin"))


;;; Generated autoloads from ecb-help.el

(autoload 'ecb-show-help "ecb-help" "\
Shows the online help of ECB in Info or HTML-format.
The format depends on the setting in `ecb-show-help-format'. If called with
prefix argument, i.e. if FORMAT is not nil then the user is prompted to choose
the format of the help (Info or Html).

If an error about not finding the needed help-file occurs please take a look
at the options `ecb-help-info-start-file' and `ecb-help-html-start-file'!

Note: If you got ECB as a standard XEmacs-package maybe the
HTML-online-documentation is not included.

(fn &optional FORMAT)" t)
(register-definition-prefixes "ecb-help" '("ecb-"))


;;; Generated autoloads from ecb-jde.el

(register-definition-prefixes "ecb-jde" '("ecb-jde-"))


;;; Generated autoloads from ecb-layout.el

(register-definition-prefixes "ecb-layout" '("balance-windows" "compilation-set-window-height" "current-window-configuration" "display-buffer" "ecb-" "enlarge-window" "mouse-drag-" "other-window" "pop-to-buffer" "resize-temp-buffer-window" "scroll-other-window" "set-window-configuration" "shrink-window" "split-window" "switch-to-buffer" "walk-windows"))


;;; Generated autoloads from ecb-layout-defs.el

(register-definition-prefixes "ecb-layout-defs" '("ecb-buildin-layouts"))


;;; Generated autoloads from ecb-method-browser.el

(register-definition-prefixes "ecb-method-browser" '("ecb-" "make-indirect-buffer"))


;;; Generated autoloads from ecb-mode-line.el

(register-definition-prefixes "ecb-mode-line" '("ecb-mode-line-"))


;;; Generated autoloads from ecb-multiframe.el

(register-definition-prefixes "ecb-multiframe" '("ecb-multiframe-variables"))


;;; Generated autoloads from ecb-navigate.el

(register-definition-prefixes "ecb-navigate" '("ecb-"))


;;; Generated autoloads from ecb-semantic.el

(register-definition-prefixes "ecb-semantic" '("ecb-"))


;;; Generated autoloads from ecb-semantic-wrapper.el

(register-definition-prefixes "ecb-semantic-wrapper" '("ecb--"))


;;; Generated autoloads from ecb-speedbar.el

(register-definition-prefixes "ecb-speedbar" '("dframe-" "ecb-" "speedbar-"))


;;; Generated autoloads from ecb-symboldef.el

(register-definition-prefixes "ecb-symboldef" '("ecb-"))


;;; Generated autoloads from ecb-tod.el

(register-definition-prefixes "ecb-tod" '("ecb-"))


;;; Generated autoloads from ecb-upgrade.el

(register-definition-prefixes "ecb-upgrade" '("ecb-"))


;;; Generated autoloads from ecb-util.el

(defconst ecb-temp-dir (file-name-as-directory (or (getenv "TMPDIR") (getenv "TMP") (getenv "TEMP") (if (eq system-type 'windows-nt) "c:/temp/" "/tmp/"))) "\
A directory where ECB can store temporary files.")
(register-definition-prefixes "ecb-util" '("defecb-multicache" "ecb-"))


;;; Generated autoloads from ecb-winman-support.el

(register-definition-prefixes "ecb-winman-support" '("ecb-winman-" "escreen-save-current-screen-configuration" "win"))


;;; Generated autoloads from silentcomp.el

(register-definition-prefixes "silentcomp" '("silentcomp-"))


;;; Generated autoloads from tree-buffer.el

(register-definition-prefixes "tree-buffer" '("CHILDREN" "tree-"))

;;; End of scraped data

(provide 'ecb-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ecb-autoloads.el ends here
